const CATS=[['Food & dining','🍜','#8065f2'],['Transport','🚕','#6294f5'],['Shopping','🛍️','#ee70a5'],['Bills & utilities','💡','#55bba0'],['Entertainment','🎬','#f2b94e'],['Health','💊','#a47be8'],['Education','📚','#56b6d8'],['Other','✦','#9ba4b8']];
const fmt=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2}), monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`, today=new Date();
let store=JSON.parse(localStorage.getItem('spendly-dashboard')||'{}'),month=monthKey(today),goal=store.goal||{name:'Emergency fund',target:50000,saved:0},charts={};
const months=document.querySelector('#monthSelect');for(let i=-6;i<=6;i++){let d=new Date(today.getFullYear(),today.getMonth()+i,1),k=monthKey(d);months.add(new Option(d.toLocaleDateString('en-IN',{month:'long',year:'numeric'}),k))}months.value=month;
function records(){return store[month]||(store[month]=[])}function persist(){store.goal=goal;localStorage.setItem('spendly-dashboard',JSON.stringify(store))}
function sums(){let arr=records(),income=arr.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0),expense=arr.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amount,0);return{arr,income,expense,balance:income-expense}}
function safe(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function categoryName(c){return CATS.find(x=>x[0]===c)||CATS[7]}
function render(){let {arr,income,expense,balance}=sums();document.querySelector('#balance').textContent=fmt(balance);document.querySelector('#income').textContent=fmt(income);document.querySelector('#expense').textContent=fmt(expense);document.querySelector('#savings').textContent=fmt(Math.max(0,balance));document.querySelector('#donutTotal').textContent=fmt(expense);document.querySelector('#expenseCaption').textContent=expense>income?'Spending exceeds income':'Spending this month';document.querySelector('#savingsCaption').textContent=balance<0?'Negative cash flow':'Income − expenses';renderGoal();renderTable(arr,'recentRows',5);renderTable(arr,'allRows',Infinity);drawCharts(arr);document.querySelector('#recentEmpty').hidden=arr.length>0;filterAll();updateInsights(income,expense,balance)}
function renderGoal(){let p=Math.min(100,goal.target?goal.saved/goal.target*100:0);['goalName','goalName2'].forEach(id=>document.getElementById(id).textContent=goal.name);['goalProgressText','goalText2'].forEach(id=>document.getElementById(id).textContent=`${fmt(goal.saved)} saved of ${fmt(goal.target)}`);['goalPercent','goalPercent2'].forEach(id=>document.getElementById(id).textContent=Math.round(p)+'%');['goalBar','goalBar2'].forEach(id=>document.getElementById(id).style.width=p+'%')}
function renderTable(arr,id,limit){let tbody=document.getElementById(id),q=document.querySelector('#searchInput').value.toLowerCase(),type=document.querySelector('#typeFilter').value,cat=document.querySelector('#categoryFilter').value;let list=[...arr].sort((a,b)=>b.date.localeCompare(a.date)).filter(x=>(!q||(x.name+' '+x.category).toLowerCase().includes(q))&&(type==='all'||x.type===type)&&(cat==='all'||x.category===cat)).slice(0,limit);tbody.innerHTML=list.map(x=>{let c=categoryName(x.category);return `<tr><td><span class="txn-name">${c[1]} &nbsp;${safe(x.name)}</span></td><td>${safe(x.category)}</td><td>${new Date(x.date+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}</td><td><span class="type-tag ${x.type}">${x.type}</span></td><td class="right">${x.type==='income'?'+':'−'}${fmt(x.amount)}</td><td><button class="row-delete" data-id="${x.id}" title="Delete transaction">×</button></td></tr>`}).join('');tbody.querySelectorAll('.row-delete').forEach(b=>b.onclick=()=>{let a=records(),i=a.findIndex(x=>x.id===b.dataset.id);if(i>=0){a.splice(i,1);persist();render();toast('Transaction deleted')}});return list.length}
function filterAll(){let n=renderTable(records(),'allRows',Infinity);document.querySelector('#allEmpty').hidden=n>0}
function drawCharts(arr){let inc=arr.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0),exp=arr.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amount,0),labels=CATS.map(c=>c[0]),vals=CATS.map(c=>arr.filter(x=>x.type==='expense'&&x.category===c[0]).reduce((s,x)=>s+x.amount,0));Object.values(charts).forEach(c=>c.destroy());charts.flow=new Chart(document.querySelector('#flowChart'),{type:'bar',data:{labels:['Income','Expenses','Savings'],datasets:[{data:[inc,exp,Math.max(0,inc-exp)],backgroundColor:['#7654f5','#fa718d','#f5c94f'],borderRadius:6,barPercentage:.55}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>fmt(c.raw)}}},scales:{x:{grid:{display:false},ticks:{font:{size:9},color:'#8992a5'}},y:{beginAtZero:true,grid:{color:'#f0f1f6'},ticks:{font:{size:8},color:'#9ba3b4',callback:v=>'₹'+v.toLocaleString('en-IN')}}}}});let has=vals.some(v=>v>0);charts.donut=new Chart(document.querySelector('#categoryChart'),{type:'doughnut',data:{labels,datasets:[{data:has?vals:labels.map((_,i)=>i===0?1:0),backgroundColor:CATS.map(c=>c[2]),borderWidth:0,hoverOffset:4}]},options:{cutout:'76%',responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>has?`${c.label}: ${fmt(c.raw)}`:'No expenses yet'}}}}});document.querySelector('#categoryLegend').innerHTML=CATS.filter((c,i)=>has?vals[i]>0:i<4).map(c=>`<div class="legend-item"><i style="background:${c[2]}"></i><span>${c[0]}</span></div>`).join('');if(document.querySelector('#analyticsChart')){charts.analytics=new Chart(document.querySelector('#analyticsChart'),{type:'bar',data:{labels,datasets:[{label:'Expenses',data:vals,backgroundColor:CATS.map(c=>c[2]),borderRadius:5}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{font:{size:9}}},y:{beginAtZero:true,grid:{color:'#f0f1f6'}}}}})}}
function updateInsights(i,e,b){document.querySelector('#savingsRate').textContent=(i>0?Math.round(b/i*100):0)+'%';document.querySelector('#insightText').textContent=i===0&&e===0?'Add income and expenses to see a summary of your spending.':b<0?`You spent ${fmt(Math.abs(b))} more than your recorded income this month. Review your expenses to understand the gap.`:`You have ${fmt(b)} left after recorded expenses. Your largest spending categories are shown in the chart.`}
function page(name){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelector('#'+name+'Page').classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===name));let labels={dashboard:['Dashboard',"Welcome back! Here's your money snapshot."],transactions:['Transactions','Review and manage your money activity.'],analytics:['Analytics','Understand your monthly spending patterns.'],goals:['Savings goals','Track progress toward what matters to you.'],settings:['Settings','Manage your dashboard and data.']};document.querySelector('#pageTitle').textContent=labels[name][0];document.querySelector('#pageSubtitle').textContent=labels[name][1];if(name==='analytics')drawCharts(records())}
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>page(n.dataset.page));months.onchange=()=>{month=months.value;render()};document.querySelector('#allTransactions').onclick=()=>page('transactions');document.querySelector('#searchInput').oninput=()=>{renderTable(records(),'recentRows',5);filterAll()};document.querySelector('#typeFilter').onchange=filterAll;document.querySelector('#categoryFilter').onchange=filterAll;
let categoryOptions=CATS.map(c=>`<option>${c[0]}</option>`).join('');document.querySelector('#entryCategory').innerHTML=categoryOptions;document.querySelector('#categoryFilter').innerHTML+='<option value="all">All categories</option>'+CATS.map(c=>`<option value="${c[0]}">${c[0]}</option>`).join('');
function openModal(id){document.querySelector(id).classList.add('show')}function close(){document.querySelectorAll('.backdrop').forEach(x=>x.classList.remove('show'))}document.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);document.querySelectorAll('.backdrop').forEach(b=>b.onclick=e=>{if(e.target===b)close()});
function addOpen(){document.querySelector('#entryDate').value=month+'-'+String(Math.min(today.getDate(),new Date(Number(month.slice(0,4)),Number(month.slice(5,7)),0).getDate())).padStart(2,'0');openModal('#transactionModal')}document.querySelector('#addBtn').onclick=addOpen;document.querySelector('#addBtn2').onclick=addOpen;
document.querySelectorAll('.type-choice').forEach(b=>b.onclick=()=>{document.querySelectorAll('.type-choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#entryType').value=b.dataset.type;document.querySelector('#entryCategory').innerHTML=categoryOptions});
document.querySelector('#transactionForm').onsubmit=e=>{e.preventDefault();let amount=Number(document.querySelector('#entryAmount').value),date=document.querySelector('#entryDate').value;if(!Number.isFinite(amount)||amount<=0)return;if(!date.startsWith(month)){toast('Select a date in the chosen month');return}records().push({id:crypto.randomUUID(),name:document.querySelector('#entryName').value.trim(),amount,category:document.querySelector('#entryCategory').value,date,type:document.querySelector('#entryType').value});persist();e.target.reset();close();render();toast('Transaction saved')};
function goalOpen(){document.querySelector('#goalInputName').value=goal.name;document.querySelector('#goalInputTarget').value=goal.target;document.querySelector('#goalInputSaved').value=goal.saved;openModal('#goalModal')}document.querySelector('#editGoal').onclick=goalOpen;document.querySelector('#editGoal2').onclick=goalOpen;document.querySelector('#goalForm').onsubmit=e=>{e.preventDefault();goal={name:document.querySelector('#goalInputName').value.trim(),target:Number(document.querySelector('#goalInputTarget').value),saved:Number(document.querySelector('#goalInputSaved').value)};persist();close();renderGoal();toast('Goal updated')};
document.querySelector('#exportData').onclick=()=>{let blob=new Blob([JSON.stringify(store,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='spendly-backup.json';a.click();URL.revokeObjectURL(url);toast('Backup exported')};document.querySelector('#clearData').onclick=()=>{if(confirm('Clear all Spendly data saved in this browser? This cannot be undone.')){localStorage.removeItem('spendly-dashboard');store={};goal={name:'Emergency fund',target:50000,saved:0};render();toast('Local data cleared')}};document.querySelector('#notify').onclick=()=>toast('You are all caught up!');document.querySelector('#userMenu').onclick=()=>toast('Personal account');let timer;function toast(s){let t=document.querySelector('#toast');t.textContent=s;t.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>t.classList.remove('show'),2200)}
render();